name: controller
description: Metadata-driven HTTP controllers without mirrors
version: 0.1.4

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  shelf: ^1.3.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.17.8
  build_runner: ^2.1.10
  controller_generator: #^0.1.4
    path: ../controller_generator
