name: controller
description: Metadata-driven HTTP controllers without mirrors
version: 0.1.5

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  shelf: ^1.4.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
  build_runner: ^2.3.2
  controller_generator: ^0.1.5
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
