name: controller
description: Metadata-driven HTTP controllers without mirrors
version: 0.1.4

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  shelf: ^0.7.5

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
