name: controller
description: Metadata-driven HTTP controllers without mirrors
version: 0.1.4

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  shelf: ^1.1.4

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.8
